### ISSUE TITLE
Consider extending the crate with merge functionality

### ISSUE THREAD

**Issue by soenkeliebau** [Arnavion/k8s-openapi#128]
We (and by that I mean @teozkr) have created functionality to `merge` objects with objects of the same type in our framework.

The use case that we are trying to solve with this is that our crds can have a hierarchy of configuration objects, with the same object being defined globally, then again for every role and every role can then have many rolegroups.

```
global/
├─ role1/
│  ├─ rolegroup11/
├─ role2/
│  ├─ rolegroup12/
│  ├─ rolegroup21/
```

When processing this, we basically iterate over all rolegroups and then need to create the config that is valid for that rolegroup by merging configs that are set "further up the tree" into the config set for this rolegroup, with anything that is "overridden" in more specific configs taking precedence.

The following example is taken from the rustdoc comments and might help make it clearer:

```rust
 # use stackable_operator::config::merge::Merge;

 #[derive(Merge, Debug, PartialEq, Eq)]
 struct Foo {
     bar: Option<u8>,
     baz: Option<u8>,
 }

 let mut config = Foo {
     bar: Some(0),
     baz: None,
 };
 config.merge(&Foo {
     bar: Some(1),
     baz: Some(2),
 });
 assert_eq!(config, Foo {
     bar: Some(0), // Overridden by `bar: Some(0)` above
     baz: Some(2), // Fallback is used
 });
```

The full code can be found [here](https://github.com/stackabletech/operator-rs/blob/16df6403f224629803f9884e04684aeced627f0a/src/config/merge.rs).

This has been working well for us, but we now do have a use case where it would be useful being able to merge structs from k8s-openapi as well.

Specifically what we'd like to do is allow users of our operators the ability to specify an "override pod template", which the operater will then merge with the pod template for statefulsets it would create before writing these.
This would allow a sort of final, catch-all mechanism to adjust operator behavior and work around missing features/bugs.

**Disclaimer**: You absolutely have to know what you are doing here! We are aware of the risks of a function like this!

That being said, there could probably be more use-cases where merging functionality might turn out useful. 

The purpose of this ticket is to check if there'd be an interest in functionality like this, we'd be happy to do the work of pulling out the code and creating a PR, but wanted to discuss the usefulness before actually doing the work :)

**Comment by Arnavion** [comment]
https://github.com/Arnavion/k8s-openapi/commit/d3718bfd050987ab6aa2d605fa94e2e7998b9385 ?

**Comment by teozkr** [comment]
Oh wow, managed to miss that completely. Will have to investigate!

**Comment by teozkr** [comment]
Hm, it looks like this doesn't implement strategic merges, right? So merging the following two documents:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nginx
    args: ["-t"]
```

Would give you the following document:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nginx
    image: nginx
  - name: nginx
    args: ["-t"]
```

But `containers` is actually an ordered map, so the correct behaviour would have been to merge the two container definitions with the same name, like so:

```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nginx
    image: nginx
    args: ["-t"]
```
