### ISSUE TITLE
Comparison of elements is too strict

### ISSUE THREAD

**Issue by anagno** [Arnavion/k8s-openapi#151]
Hello and thank you for the great project !

I have a use case that I want to compare some deployments and see if they are equal. Let`s take for example the below 2 deployments:

```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: test
spec:
    replicas: 1
    template:
        spec:
            containers:
                - env:
                    - name: test
                      valueFrom:
                        configMapKeyRef:
                            name: test
                            key: test
                    - name: test2
                      valueFrom:
                        configMapKeyRef:
                            name: test2
                            key: test2
                  name: test
                  image: test:2.0.0
                  imagePullPolicy: IfNotPresent
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: test
spec:
    replicas: 1
    template:
        spec:
            containers:
                - env:
                    - name: test2
                      valueFrom:
                        configMapKeyRef:
                            name: test2
                            key: test2
                    - name: test
                      valueFrom:
                        configMapKeyRef:
                            name: test
                            key: test
                  name: test
                  image: test:2.0.0
                  imagePullPolicy: IfNotPresent
```

The only difference of these deployments is the order of the environmental variables. 

When we compare them using the crate, the comparison returns false. Is that expected?
Is there a way of comparing and ignoring the order of the elements?

I am guessing this would also happen for other elements and Kinds

KR,

Vasileios
