### ISSUE TITLE
int-or-string parameters are typed out with mismatched "type" property

### ISSUE THREAD

**Issue by zlepper** [Arnavion/k8s-openapi#152]
According to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#intorstring types that are of the format "int-or-string" should be typed like this in the schema:

```yaml
type: object
properties:
  foo:
    x-kubernetes-int-or-string: true
```
However right now they are typed as:

```yaml
type: object
properties:
  foo:
     type: string
     format: int-or-string
```

While it probably isn't an issue most of the time, i'm encountering conflicts with reusing PodTemplateSpec, specially for `httpGetAction` for probes ends up like this:
```yaml
                                          port:
                                            description: >-
                                              Name or number of the port to access on
                                              the container. Number must be in the
                                              range 1 to 65535. Name must be an
                                              IANA_SVC_NAME.
                                            type: string
                                            format: int-or-string
```
whereas they should probably end like this:
```yaml

                                          port:
                                            description: >-
                                              Name or number of the port to access on
                                              the container. Number must be in the
                                              range 1 to 65535. Name must be an
                                              IANA_SVC_NAME.
                                            x-kubernetes-int-or-string: true
```

If left as is, you have to put quotes around the port number to be allowed to create an instance of a CRD resource with this property, however when you then try to create a pod from this spec, it will fail as quoted values are considered to the names of the named ports.
